DROP TABLE IF EXISTS FLIGHTS;
CREATE TABLE FLIGHTS (
  flight_id   INTEGER NOT NULL AUTO_INCREMENT,
  flight VARCHAR(45) NOT NULL,
  date_flight DATE,
  PRIMARY KEY (flight_id)
);
DROP TABLE IF EXISTS CUSTOMER_LIST;
CREATE TABLE CUSTOMER_LIST (
  customer_id    INTEGER NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(45) NOT NULL,
  lastname VARCHAR(45) NOT NULL,
  flight_id   INTEGER NOT NULL,
  PRIMARY KEY (customer_id),
  CONSTRAINT customer_list_to_flight_schedule_fk
	FOREIGN KEY (flight_id)
	REFERENCES CUSTOMER_LIST (flight_id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
);
