INSERT INTO flights  (FLIGHT_ID ,FLIGHT, DATE_FLIGHT  ) VALUES (101, 'Minsk-Berlin', '2020-04-11');
INSERT INTO flights  (FLIGHT, DATE_FLIGHT  ) VALUES ('Minsk-Frankfort', '2020-04-12');
INSERT INTO flights  (FLIGHT, DATE_FLIGHT  ) VALUES ('Minsk-Moscow', '2020-04-10');
INSERT INTO flights  (FLIGHT, DATE_FLIGHT  ) VALUES ('Minsk-Paris', '2020-04-15');
INSERT INTO flights  (FLIGHT, DATE_FLIGHT  ) VALUES ('Minsk-Brest', '2020-04-09');

INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Michail', 'Ivanov',101);
INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Nickolai', 'Kroch',105);
INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Ann', 'Loza',101);
INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Sonia', 'Govin',104);
INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Alex', 'Kroch',101);
INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Michail', 'Petrov',102);
INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Ann', 'Tromza',102);
INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Ivan', 'Kovalev',101);
INSERT INTO passengers   (FIRSTNAME ,LASTNAME ,FLIGHT_ID  ) VALUES ('Nickolai', 'Loza',105);